name:                aguda
version:             0.1.0.0
github:              "githubuser/aguda"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aguda#readme>

dependencies:
- base >= 4.7 && < 5
- array <= 0.5.8.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aguda-exe:
    main:                Main.hs
    source-dirs:         app
    build-tools:
    - alex
    - happy
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aguda


tests:
  aguda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aguda
    - hspec >= 2.7.1       
    - directory >= 1.3.2.0
    - filepath >= 1.4.2.2
    - HUnit >= 1.6.2.0

default-extensions:
  - ImportQualifiedPost
